[workspace]
members = [
	"uywi",
	"uywi-web"
]

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"

[profile.test]
opt-level = 3
lto = true
codegen-units = 1
incremental = false
