cargo-features = ["named-profiles"]

[workspace]
members = [
	"uywi",
	"uywi-web"
]

[profile.release]
lto = true
codegen-units = 1

[profile.release-web]
inherits = "release"
opt-level = "s"
panic = "abort"
