extend = "Makefile-internals.toml"

[tasks.build]
workspace = false
dependencies = ["internal-build"]

[tasks.run]
workspace = false
dependencies = ["internal-run"]

[tasks.check]
workspace = false
dependencies = ["internal-check"]

[tasks.test]
workspace = false
dependencies = ["internal-test"]

[tasks.doc]
dependencies = ["internal-doc"]

[tasks.serve]
workspace = false
dependencies = ["internal-serve"]
