unstable_features = true
edition = "2018"
hard_tabs = true
control_brace_style = "ClosingNextLine"
trailing_comma = "Never"
match_block_trailing_comma = true
newline_style = "Unix"
max_width = 150
merge_imports = true
